export enum PromptEnum {
    ADMIN_WELCOME_MESSAGE_SETUP_PROMPT = 'WELCOME_MESSAGE_SETUP_PROMPT',
    ADMIN_WORKFLOW_DETECTION_PROMPT = 'ADMIN_WORKFLOW_DETECTION_PROMPT',
    ADMIN_CHANNEL_RECOMMENDATIONS_PROMPT = 'ADMIN_CHANNEL_RECOMMENDATIONS_PROMPT',
    ADMIN_SERVER_RULES_PROMPT = 'ADMIN_SERVER_RULES',
    ADMIN_SEND_MESSAGE = 'ADMIN_SEND_MESSAGE',
    USER_WORKFLOW_DETECTION_PROMPT = 'USER_WORKFLOW_DETECTION_PROMPT',
    USER_COMMAND_EXECUTE_PROMPT = 'USER_COMMAND_EXECUTE_PROMPT',
    USER_COMMAND_SYSTEM_PROMPT = 'USER_COMMAND_SYSTEM_PROMPT',
    USER_CHANNEL_RECOMMENDATIONS_PROMPT = 'USER_CHANNEL_RECOMMENDATIONS_PROMPT',
}
